# .github/issue-branch.yml

# GitHub Action: Issue Branch
on:
  issues:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  create_branch:
    # 이슈가 열렸을 때만 실행 (선택적)
    if: github.event.action == 'opened' || github.event.action == 'labeled'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Calculate Branch Variables
        id: calculate_vars
        run: |
          # 1. ISSUE NUMBER (필수)
          ISSUE_NUMBER=${{ github.event.issue.number }}
          
          # 2. MILESTONE (마일스톤 부재 시 common)
          MILESTONE_TITLE="${{ github.event.issue.milestone.title }}"
          if [ -z "$MILESTONE_TITLE" ]; then
            MILESTONE_SLUG="common"
          else
            # 소문자 변환 및 공백/특수문자 처리
            MILESTONE_SLUG=$(echo "$MILESTONE_TITLE" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]\n' '-')
          fi
          
          # 3. LABELS (레이블 다수 시 common)
          LABEL_ARRAY='${{ toJson(github.event.issue.labels.*.name) }}'
          LABEL_COUNT=$(echo "$LABEL_ARRAY" | grep -o ',' | wc -l)
          LABEL_COUNT=$((LABEL_COUNT + 1))
          
          if [ "$LABEL_COUNT" -gt 1 ]; then
            LABEL_SLUG="common"
          else
            # 레이블이 1개일 경우 해당 레이블 사용 (슬러그 처리)
            # 레이블이 0개일 경우, common이 아닌 'no-label' 등 다른 명시적 값도 고려 가능 (여기서는 1개 이하로 간주하고 첫 번째 레이블 사용)
            FIRST_LABEL=$(echo "$LABEL_ARRAY" | sed -n 's/^\["\(.*\)"\]/\1/p')
            if [ -z "$FIRST_LABEL" ]; then
              LABEL_SLUG="no-label" # 레이블이 없는 경우 처리
            else
              LABEL_SLUG=$(echo "$FIRST_LABEL" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]\n' '-')
            fi
          fi
          
          # 4. ISSUE TYPE (커밋 컨벤션 스타일을 ISSUE_TEMPLATE을 통해 가져온다고 가정 - 아래 2번 참고)
          # 'Issue Type' 레이블을 검색하거나, 이슈 본문에서 특정 값을 추출하는 로직이 필요.
          # 여기서는 'Issue Type'이 'type-fix', 'type-feat' 등의 레이블로 존재한다고 임시 가정.
          # 실제 구현에서는 이슈 본문의 커스텀 필드에서 추출해야 합니다.
          # **임시 로직:** 'type-'으로 시작하는 레이블을 Issue Type으로 간주하고, 없으면 'misc'로 처리.
          ISSUE_TYPE_LABEL=$(echo "$LABEL_ARRAY" | grep -oE '"type-[^"]*"' | head -1 | sed 's/"//g' | sed 's/type-//')
          
          if [ -z "$ISSUE_TYPE_LABEL" ]; then
            ISSUE_TYPE_SLUG="misc"
          else
            ISSUE_TYPE_SLUG=$(echo "$ISSUE_TYPE_LABEL" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]\n' '-')
          fi
          
          # 5. WORKER (user.name 기반, 없으면 SKIP)
          # 사용자 이름에는 특수문자가 있을 수 있으므로 슬러그 처리
          USER_NAME="${{ github.event.issue.user.login }}"
          if [ -z "$USER_NAME" ]; then
            WORKER_SLUG=""
          else
            WORKER_SLUG=$(echo "$USER_NAME" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]\n' '-')
            # Worker가 있으면 접두사 '-' 추가
            WORKER_SLUG="-$WORKER_SLUG"
          fi

          # 최종 브랜치 이름 구성
          BRANCH_NAME="${MILESTONE_SLUG}/${LABEL_SLUG}/${ISSUE_TYPE_SLUG}/${ISSUE_NUMBER}${WORKER_SLUG}"
          
          # GitHub Action 결과 변수로 설정
          echo "MILESTONE_SLUG=$MILESTONE_SLUG" >> $GITHUB_OUTPUT
          echo "LABEL_SLUG=$LABEL_SLUG" >> $GITHUB_OUTPUT
          echo "ISSUE_TYPE_SLUG=$ISSUE_TYPE_SLUG" >> $GITHUB_OUTPUT
          echo "WORKER_SLUG=$WORKER_SLUG" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
          
          echo "Generated Branch Name: $BRANCH_NAME"

      - name: Create Issue Branch
        uses: peterjgrainger/action-issue-branch@v2.2.0
        with:
          # 위 step에서 계산한 최종 브랜치 이름 사용
          branch-name: ${{ steps.calculate_vars.outputs.BRANCH_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          # 이슈가 닫힐 때 브랜치 자동 삭제 (선택 사항)
          delete-branch-on-close: true