"""1st initialize db

Revision ID: 07aa828a0237
Revises: fa2e0acc74d6
Create Date: 2025-11-25 20:07:53.933756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07aa828a0237'
down_revision: Union[str, Sequence[str], None] = 'fa2e0acc74d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'knowledge_edges', 'origin_data', ['target_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'knowledge_edges', 'sys_dict', ['predicate_id'], ['id'])
    op.create_foreign_key(None, 'knowledge_edges', 'origin_data', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'origin_data', 'sys_dict', ['src_sys_id'], ['id'])
    op.create_foreign_key(None, 'origin_data', 'sys_dict', ['dtype_id'], ['id'])
    op.create_foreign_key(None, 'origin_data', 'revisions', ['curr_rev_id'], ['id'])
    op.create_foreign_key(None, 'revisions', 'sys_dict', ['editor_id'], ['id'])
    op.create_foreign_key(None, 'revisions', 'origin_data', ['data_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'revisions', 'blob_store', ['summary_hash'], ['hash'])
    op.create_foreign_key(None, 'tree_nodes', 'origin_data', ['data_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tree_nodes', 'tree_nodes', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tree_nodes', type_='foreignkey')
    op.drop_constraint(None, 'tree_nodes', type_='foreignkey')
    op.drop_constraint(None, 'revisions', type_='foreignkey')
    op.drop_constraint(None, 'revisions', type_='foreignkey')
    op.drop_constraint(None, 'revisions', type_='foreignkey')
    op.drop_constraint(None, 'origin_data', type_='foreignkey')
    op.drop_constraint(None, 'origin_data', type_='foreignkey')
    op.drop_constraint(None, 'origin_data', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_edges', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_edges', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_edges', type_='foreignkey')
    # ### end Alembic commands ###
