"""Initial migration

Revision ID: 22416cb2568f
Revises: 
Create Date: 2025-01-27

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22416cb2568f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchors',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.Enum('GITHUB', 'FILESYSTEM', 'TODO', 'CALENDAR', name='anchortype'), nullable=False),
    sa.Column('locator', sa.String(length=1024), nullable=False),
    sa.Column('origin_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anchors_created_at', 'anchors', ['created_at'], unique=False)
    op.create_index('ix_anchors_type', 'anchors', ['type'], unique=False)
    op.create_index('ix_anchors_locator', 'anchors', ['locator'], unique=True)
    op.create_table('virtual_pages',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('anchor_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('content_description', sa.Text(), nullable=True),
    sa.Column('outline_document_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['anchor_id'], ['anchors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anchor_id')
    )
    op.create_index('ix_virtual_pages_created_at', 'virtual_pages', ['created_at'], unique=False)
    op.create_index('ix_virtual_pages_outline_document_id', 'virtual_pages', ['outline_document_id'], unique=False)
    op.create_table('revisions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('virtual_page_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('content_snapshot', sa.Text(), nullable=True),
    sa.Column('revision_notes', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['virtual_page_id'], ['virtual_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_revisions_created_at', 'revisions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revisions_created_at', table_name='revisions')
    op.drop_table('revisions')
    op.drop_index('ix_virtual_pages_outline_document_id', table_name='virtual_pages')
    op.drop_index('ix_virtual_pages_created_at', table_name='virtual_pages')
    op.drop_table('virtual_pages')
    op.drop_index(op.f('ix_anchors_locator'), table_name='anchors')
    op.drop_index('ix_anchors_type', table_name='anchors')
    op.drop_index('ix_anchors_locator', table_name='anchors')
    op.drop_index('ix_anchors_created_at', table_name='anchors')
    op.drop_table('anchors')
    op.execute('DROP TYPE IF EXISTS anchortype')
    # ### end Alembic commands ###

