"""1st_migration

Revision ID: fa2e0acc74d6
Revises: 
Create Date: 2025-11-25 19:58:38.948480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa2e0acc74d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blob_store',
    sa.Column('hash', sa.CHAR(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('body', postgresql.BYTEA(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('origin_data',
    sa.Column('urn', sa.String(length=255), nullable=False),
    sa.Column('src_sys_id', sa.BigInteger(), nullable=False),
    sa.Column('dtype_id', sa.BigInteger(), nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.Column('curr_rev_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urn')
    )
    op.create_table('revisions',
    sa.Column('data_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('summary_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('editor_id', sa.BigInteger(), nullable=False),
    sa.Column('meta_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_dict',
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('val', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'val', name='uq_sys_dict_cat_val')
    )
    op.create_table('knowledge_edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('predicate_id', sa.BigInteger(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'predicate_id', name='uq_edge_src_tgt_pred')
    )
    op.create_table('tree_nodes',
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('data_id', sa.BigInteger(), nullable=True),
    sa.Column('view_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('view_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    # sa.ForeignKeyConstraint(['predicate_id'], ['sys_dict.id'], ),
    # sa.ForeignKeyConstraint(['source_id'], ['origin_data.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['target_id'], ['origin_data.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['data_id'], ['origin_data.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['editor_id'], ['sys_dict.id'], ),
    # sa.ForeignKeyConstraint(['summary_hash'], ['blob_store.hash'], ),
    # sa.ForeignKeyConstraint(['curr_rev_id'], ['revisions.id'], ),
    # sa.ForeignKeyConstraint(['dtype_id'], ['sys_dict.id'], ),
    # sa.ForeignKeyConstraint(['src_sys_id'], ['sys_dict.id'], ),
    # sa.ForeignKeyConstraint(['data_id'], ['origin_data.id'], ondelete='SET NULL'),
    # sa.ForeignKeyConstraint(['parent_id'], ['tree_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', 'view_type', name='uq_tree_node_sibling')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tree_nodes')
    op.drop_table('knowledge_edges')
    op.drop_table('sys_dict')
    op.drop_table('revisions')
    op.drop_table('origin_data')
    op.drop_table('blob_store')
    # ### end Alembic commands ###
